### ISSUE TITLE
Label confirm.text can be misleading

### ISSUE THREAD

**Issue by derfony** [bash/exif_orientation_helper#2]
Before rotating an image a dialogue warns editors that this action "replaces the original image and discards metadata associated with it". This is true as exif metadata will be lost. I find it misleading for editors though. I supposed quite a lot of editors do not know about the existence of exif metadata. They might think that metadata they added to the image in TYPO3 will be lost, when in fact metadata stored in ```sys_file_metadata``` remains intact (except for ```sys_file_metadata.title```, but this is another issue).

**Comment by tautropfli** [comment]
What do you think about rephrasing the text as follows?
> This action replaces the original image and discards all EXIF metadata associated with the image. Metadata entered through the TYPO3 Backend will not be affected.

**Comment by derfony** [comment]
I came up with "Metadata associated with the image that is stored in TYPO3 remains untouched." (bzw. "Metadaten, die in TYPO3 zu diesem Bild gespeichert sind, bleiben dagegen erhalten." für die deutsche Version) but yours actually sounds a little clearer. Very helpful extension btw!
